import { useMemo, useState } from 'react'
import type { Service } from '../types'
import { Badge, Empty, Field, Icon, Modal, PageHeader, Progress } from '../components/UI'

const tone = (value:string) => value==='Kritická'?'danger':value==='Vysoká'?'warning':value==='Stredná'?'info':'neutral'

function readiness(service: Service) {
  const checks=[service.businessOwner,service.technicalOwner,service.deputy,service.rto,service.runbook,service.repository,service.monitoring,service.backup]
  return Math.round(checks.filter(Boolean).length/checks.length*100)
}

export default function Services({ services, canEdit, onChange }: { services: Service[]; canEdit: boolean; onChange:(services:Service[])=>void }) {
  const [search,setSearch]=useState('')
  const [criticality,setCriticality]=useState('Všetky')
  const [selected,setSelected]=useState<Service|null>(null)
  const [editing,setEditing]=useState<Service|null>(null)
  const filtered=useMemo(()=>services.filter(s=>(criticality==='Všetky'||s.criticality===criticality)&&`${s.name} ${s.category} ${s.primary} ${s.businessOwner} ${s.technicalOwner}`.toLowerCase().includes(search.toLowerCase())),[services,search,criticality])
  function save(){if(!editing)return;onChange(services.map(s=>s.id===editing.id?editing:s));setSelected(editing);setEditing(null)}
  return <>
    <PageHeader eyebrow="Portfólio služieb" title="Kritické služby a systémy" description="Vlastníctvo, vykonávatelia, zástupcovia, dokumentácia, monitoring, zálohovanie a pripravenosť služby." />
    <div className="toolbar toolbar-wrap"><div className="search-box"><Icon name="search" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Hľadať službu alebo vlastníka…"/></div><select value={criticality} onChange={e=>setCriticality(e.target.value)}><option>Všetky</option><option>Kritická</option><option>Vysoká</option><option>Stredná</option></select><Badge tone="info">{filtered.length} služieb</Badge></div>
    {filtered.length===0?<Empty title="Žiadne služby" text="Zmeň vyhľadávanie alebo filter."/>:<div className="service-grid">{filtered.map(service=><button className="service-card" key={service.id} onClick={()=>setSelected(service)}><div className="service-card-top"><div className="service-icon"><Icon name="services"/></div><Badge tone={tone(service.criticality)}>{service.criticality}</Badge></div><h3>{service.name}</h3><p>{service.category}</p><div className="service-owners"><span><small>Primárny vykonávateľ</small><strong>{service.primary||'Neurčený'}</strong></span><span><small>Zástupca</small><strong className={!service.deputy?'danger-text':''}>{service.deputy||'Chýba'}</strong></span></div><Progress value={readiness(service)} label="Pripravenosť"/><div className="card-link">Detail služby <Icon name="arrow" size={15}/></div></button>)}</div>}
    {selected&&<Modal title={selected.name} onClose={()=>setSelected(null)} wide><div className="profile-header"><div className="service-icon service-icon-large"><Icon name="services" size={28}/></div><div><Badge tone={tone(selected.criticality)}>{selected.criticality}</Badge><h3>{selected.category}</h3><p>{selected.readiness}</p></div>{canEdit&&<button className="button button-secondary profile-edit" onClick={()=>setEditing({...selected})}><Icon name="edit"/> Upraviť</button>}</div><div className="detail-grid"><section><h4>Biznis vlastník</h4><p>{selected.businessOwner||'Neurčený'}</p></section><section><h4>Technický vlastník</h4><p>{selected.technicalOwner||'Neurčený'}</p></section><section><h4>Primárny vykonávateľ</h4><p>{selected.primary||'Neurčený'}</p></section><section><h4>Zástupca</h4><p>{selected.deputy||'Neurčený'}</p></section><section><h4>RTO / tolerovaný výpadok</h4><p>{selected.rto||'Nedoplnené'}</p></section><section><h4>Dodávateľ / SLA</h4><p>{selected.supplierSla||'Nedoplnené'}</p></section><section><h4>Runbook</h4><p>{selected.runbook||'Nedoplnené'}</p></section><section><h4>Repozitár</h4><p>{selected.repository||'Nedoplnené'}</p></section><section><h4>Monitoring</h4><p>{selected.monitoring||'Nedoplnené'}</p></section><section><h4>Zálohovanie</h4><p>{selected.backup||'Nedoplnené'}</p></section><section className="full"><h4>Poznámka</h4><p>{selected.note||'Bez poznámky'}</p></section></div></Modal>}
    {editing&&<Modal title={`Upraviť službu: ${editing.name}`} onClose={()=>setEditing(null)} wide><div className="form-grid"><Field label="Názov"><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="Kategória"><input value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/></Field><Field label="Kritickosť"><select value={editing.criticality} onChange={e=>setEditing({...editing,criticality:e.target.value})}><option>Kritická</option><option>Vysoká</option><option>Stredná</option><option>Nízka</option></select></Field><Field label="Stav pripravenosti"><select value={editing.readiness} onChange={e=>setEditing({...editing,readiness:e.target.value})}><option>Na potvrdenie</option><option>Rozpracované</option><option>Schválené</option></select></Field><Field label="Biznis vlastník"><input value={editing.businessOwner} onChange={e=>setEditing({...editing,businessOwner:e.target.value})}/></Field><Field label="Technický vlastník"><input value={editing.technicalOwner} onChange={e=>setEditing({...editing,technicalOwner:e.target.value})}/></Field><Field label="Primárny vykonávateľ"><input value={editing.primary} onChange={e=>setEditing({...editing,primary:e.target.value})}/></Field><Field label="Zástupca"><input value={editing.deputy} onChange={e=>setEditing({...editing,deputy:e.target.value})}/></Field><Field label="RTO"><input value={editing.rto} onChange={e=>setEditing({...editing,rto:e.target.value})}/></Field><Field label="Runbook"><input value={editing.runbook} onChange={e=>setEditing({...editing,runbook:e.target.value})}/></Field><Field label="Repozitár"><input value={editing.repository} onChange={e=>setEditing({...editing,repository:e.target.value})}/></Field><Field label="Monitoring"><input value={editing.monitoring} onChange={e=>setEditing({...editing,monitoring:e.target.value})}/></Field><Field label="Zálohovanie"><input value={editing.backup} onChange={e=>setEditing({...editing,backup:e.target.value})}/></Field><Field label="Dodávateľ / SLA"><input value={editing.supplierSla} onChange={e=>setEditing({...editing,supplierSla:e.target.value})}/></Field><Field label="Poznámka"><textarea value={editing.note} onChange={e=>setEditing({...editing,note:e.target.value})}/></Field></div><div className="modal-actions"><button className="button button-ghost" onClick={()=>setEditing(null)}>Zrušiť</button><button className="button button-primary" onClick={save}><Icon name="check"/> Uložiť</button></div></Modal>}
  </>
}
