import { useMemo, useState } from 'react'
import type { Risk } from '../types'
import { Badge, Field, Icon, Modal, PageHeader } from '../components/UI'

function priority(score:number){return score>=20?'Kritická':score>=12?'Vysoká':score>=6?'Stredná':'Nízka'}
function tone(p:string){return p==='Kritická'?'danger':p==='Vysoká'?'warning':p==='Stredná'?'info':'neutral'}

export default function Risks({risks,canEdit,onChange}:{risks:Risk[];canEdit:boolean;onChange:(r:Risk[])=>void}){
  const [filter,setFilter]=useState('Všetky')
  const [selected,setSelected]=useState<Risk|null>(null)
  const [editing,setEditing]=useState<Risk|null>(null)
  const filtered=useMemo(()=>risks.filter(r=>filter==='Všetky'||priority(r.probability*r.impactScore)===filter).sort((a,b)=>b.probability*b.impactScore-a.probability*a.impactScore),[risks,filter])
  function save(){if(!editing)return;const updated={...editing,priority:priority(editing.probability*editing.impactScore)};onChange(risks.map(r=>r.id===updated.id?updated:r));setSelected(updated);setEditing(null)}
  return <>
    <PageHeader eyebrow="Kontrola" title="Register rizík" description="Riziká odboru, ich vlastníci, skóre, nápravné opatrenia a rozhodnutia potrebné na úrovni vedenia." />
    <div className="toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Všetky</option><option>Kritická</option><option>Vysoká</option><option>Stredná</option><option>Nízka</option></select><Badge tone="info">{filtered.length} rizík</Badge></div>
    <div className="table-shell"><table className="data-table"><thead><tr><th>Skóre</th><th>Oblasť a riziko</th><th>Vlastník</th><th>Opatrenie</th><th>Stav</th></tr></thead><tbody>{filtered.map(r=>{const score=r.probability*r.impactScore;const p=priority(score);return <tr key={r.id} onClick={()=>setSelected(r)} className="clickable-row"><td><div className={`risk-score risk-score-${p.toLowerCase()}`}>{score}</div></td><td><div className="table-primary"><div><Badge tone={tone(p)}>{p}</Badge><span>{r.id} · {r.area}</span></div><strong>{r.risk}</strong><small>{r.impact}</small></div></td><td>{r.owner||'Neurčený'}</td><td className="wide-text">{r.measure}</td><td><Badge tone={r.status==='Ukončené'?'success':'warning'}>{r.status}</Badge></td></tr>})}</tbody></table></div>
    {selected&&<Modal title={`${selected.id} · ${selected.area}`} onClose={()=>setSelected(null)} wide><div className="profile-header"><div className="risk-score risk-score-large">{selected.probability*selected.impactScore}</div><div><Badge tone={tone(priority(selected.probability*selected.impactScore))}>{priority(selected.probability*selected.impactScore)}</Badge><h3>{selected.risk}</h3><p>{selected.owner||'Vlastník neurčený'}</p></div>{canEdit&&<button className="button button-secondary profile-edit" onClick={()=>setEditing({...selected})}><Icon name="edit"/> Upraviť</button>}</div><div className="detail-grid"><section><h4>Spúšťač / príčina</h4><p>{selected.trigger}</p></section><section><h4>Dopad</h4><p>{selected.impact}</p></section><section><h4>Navrhované opatrenie</h4><p>{selected.measure}</p></section><section><h4>Rozhodnutie vedenia</h4><p>{selected.managementDecision||'Nedoplnené'}</p></section><section><h4>Pravdepodobnosť</h4><p>{selected.probability} / 5</p></section><section><h4>Dopad</h4><p>{selected.impactScore} / 5</p></section></div></Modal>}
    {editing&&<Modal title={`Upraviť riziko: ${editing.id}`} onClose={()=>setEditing(null)} wide><div className="form-grid"><Field label="Riziko"><textarea value={editing.risk} onChange={e=>setEditing({...editing,risk:e.target.value})}/></Field><Field label="Vlastník"><input value={editing.owner} onChange={e=>setEditing({...editing,owner:e.target.value})}/></Field><Field label="Pravdepodobnosť 1–5"><input type="number" min="1" max="5" value={editing.probability} onChange={e=>setEditing({...editing,probability:Number(e.target.value)})}/></Field><Field label="Dopad 1–5"><input type="number" min="1" max="5" value={editing.impactScore} onChange={e=>setEditing({...editing,impactScore:Number(e.target.value)})}/></Field><Field label="Stav"><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option>Otvorené</option><option>Rieši sa</option><option>Akceptované</option><option>Ukončené</option></select></Field><Field label="Termín"><input type="date" value={editing.due} onChange={e=>setEditing({...editing,due:e.target.value})}/></Field><Field label="Opatrenie"><textarea value={editing.measure} onChange={e=>setEditing({...editing,measure:e.target.value})}/></Field><Field label="Rozhodnutie vedenia"><textarea value={editing.managementDecision} onChange={e=>setEditing({...editing,managementDecision:e.target.value})}/></Field></div><div className="modal-actions"><button className="button button-ghost" onClick={()=>setEditing(null)}>Zrušiť</button><button className="button button-primary" onClick={save}><Icon name="check"/> Uložiť</button></div></Modal>}
  </>
}
