import { useState } from 'react'
import type { Decision } from '../types'
import { Badge, Field, Icon, Modal, PageHeader } from '../components/UI'

export default function Decisions({items,canEdit,onChange}:{items:Decision[];canEdit:boolean;onChange:(d:Decision[])=>void}){
  const [editing,setEditing]=useState<Decision|null>(null)
  function save(){if(!editing)return;onChange(items.map(i=>i.id===editing.id?editing:i));setEditing(null)}
  return <>
    <PageHeader eyebrow="Manažérske rozhodovanie" title="Otvorené rozhodnutia" description="Témy, ktoré nie je vhodné ponechať iba na operatívnej úrovni a vyžadujú formálne rozhodnutie alebo mandát." />
    <div className="decision-cards">{items.map(item=><article className="decision-card" key={item.id}><header><span>{item.id}</span><Badge tone={item.status==='Schválené'?'success':'warning'}>{item.status}</Badge></header><small>{item.topic}</small><h3>{item.question}</h3><div className="decision-proposal"><strong>Pracovný návrh</strong><p>{item.proposal}</p></div><footer><span><Icon name="user" size={15}/>{item.decisionMaker}</span>{canEdit&&<button className="icon-button" onClick={()=>setEditing({...item})}><Icon name="edit" size={17}/></button>}</footer>{item.decision&&<div className="approved-decision"><Icon name="check" size={17}/><div><strong>Rozhodnutie</strong><p>{item.decision}</p></div></div>}</article>)}</div>
    {editing&&<Modal title={`Rozhodnutie ${editing.id}`} onClose={()=>setEditing(null)} wide><div className="form-grid"><Field label="Téma"><input value={editing.topic} onChange={e=>setEditing({...editing,topic:e.target.value})}/></Field><Field label="Rozhodovateľ"><input value={editing.decisionMaker} onChange={e=>setEditing({...editing,decisionMaker:e.target.value})}/></Field><Field label="Stav"><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option>Návrh</option><option>Na prerokovanie</option><option>Schválené</option><option>Zamietnuté</option></select></Field><Field label="Termín"><input type="date" value={editing.due} onChange={e=>setEditing({...editing,due:e.target.value})}/></Field><Field label="Otázka"><textarea value={editing.question} onChange={e=>setEditing({...editing,question:e.target.value})}/></Field><Field label="Pracovný návrh"><textarea value={editing.proposal} onChange={e=>setEditing({...editing,proposal:e.target.value})}/></Field><Field label="Rozhodnutie"><textarea value={editing.decision} onChange={e=>setEditing({...editing,decision:e.target.value})}/></Field><Field label="Dôvod / podklad"><textarea value={editing.reason} onChange={e=>setEditing({...editing,reason:e.target.value})}/></Field></div><div className="modal-actions"><button className="button button-ghost" onClick={()=>setEditing(null)}>Zrušiť</button><button className="button button-primary" onClick={save}><Icon name="check"/> Uložiť</button></div></Modal>}
  </>
}
