import { useMemo, useState } from 'react'
import type { Substitution } from '../types'
import { Badge, Field, Icon, Modal, PageHeader, Progress } from '../components/UI'

export default function Substitutions({ items, canEdit, onChange }: { items:Substitution[]; canEdit:boolean; onChange:(items:Substitution[])=>void }) {
  const [selected,setSelected]=useState<Substitution|null>(null)
  const [filter,setFilter]=useState('Všetky')
  const [editing,setEditing]=useState<Substitution|null>(null)
  const filtered=useMemo(()=>items.filter(i=>filter==='Všetky'||i.currentState===filter),[items,filter])
  function score(i:Substitution){return [i.confirmedDeputy,i.runbook,i.location,i.testDate].filter(Boolean).length*25}
  function save(){if(!editing)return;onChange(items.map(i=>i.id===editing.id?editing:i));setSelected(editing);setEditing(null)}
  return <>
    <PageHeader eyebrow="Kontinuita" title="Zastupiteľnosť a odovzdanie know-how" description="Zástupca je pripravený až po potvrdení osoby, odovzdaní runbooku, prístupov a praktickom teste zastúpenia." />
    <div className="toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Všetky</option><option>Žiadna</option><option>V príprave</option><option>Čiastočná</option><option>Plná</option></select><Badge tone="info">{filtered.length} agend</Badge></div>
    <div className="substitution-grid">{filtered.map(item=>{const s=score(item);return <button className="substitution-card" key={item.id} onClick={()=>setSelected(item)}><div className="substitution-card-head"><span>{item.id}</span><Badge tone={s>=75?'success':s>=50?'info':s>=25?'warning':'danger'}>{item.currentState}</Badge></div><h3>{item.agenda}</h3><p><strong>Vlastník:</strong> {item.owner}</p><p><strong>Návrh zástupcu:</strong> {item.proposedDeputy||'Neurčený'}</p><Progress value={s} label="Pripravenosť zastúpenia"/><div className="check-row"><span className={item.confirmedDeputy?'done':''}><Icon name={item.confirmedDeputy?'check':'warning'} size={15}/> osoba</span><span className={item.runbook?'done':''}><Icon name={item.runbook?'check':'warning'} size={15}/> runbook</span><span className={item.testDate?'done':''}><Icon name={item.testDate?'check':'warning'} size={15}/> test</span></div></button>})}</div>
    {selected&&<Modal title={selected.agenda} onClose={()=>setSelected(null)} wide><div className="profile-header"><div className="service-icon service-icon-large"><Icon name="substitute" size={28}/></div><div><Badge tone={score(selected)>=75?'success':'warning'}>{selected.currentState}</Badge><h3>{selected.owner}</h3><p>Primárny vlastník</p></div>{canEdit&&<button className="button button-secondary profile-edit" onClick={()=>setEditing({...selected})}><Icon name="edit"/> Upraviť</button>}</div><div className="detail-grid"><section><h4>Navrhovaný zástupca</h4><p>{selected.proposedDeputy||'Neurčený'}</p></section><section><h4>Potvrdený zástupca</h4><p>{selected.confirmedDeputy||'Neurčený'}</p></section><section><h4>Rozsah zastúpenia</h4><p>{selected.scope||'Nedoplnené'}</p></section><section><h4>Minimálny runbook</h4><p>{selected.runbook||'Nedoplnené'}</p></section><section><h4>Miesto dokumentácie</h4><p>{selected.location||'Nedoplnené'}</p></section><section><h4>Termín odovzdania</h4><p>{selected.handoverDue||'Neurčený'}</p></section><section><h4>Dátum testu</h4><p>{selected.testDate||'Neurčený'}</p></section><section><h4>Výsledok testu</h4><p>{selected.testResult||'Nedoplnené'}</p></section><section className="full"><h4>Poznámka</h4><p>{selected.note||'Bez poznámky'}</p></section></div></Modal>}
    {editing&&<Modal title={`Upraviť zastupiteľnosť: ${editing.agenda}`} onClose={()=>setEditing(null)} wide><div className="form-grid"><Field label="Súčasný stav"><select value={editing.currentState} onChange={e=>setEditing({...editing,currentState:e.target.value})}><option>Žiadna</option><option>V príprave</option><option>Čiastočná</option><option>Plná</option></select></Field><Field label="Primárny vlastník"><input value={editing.owner} onChange={e=>setEditing({...editing,owner:e.target.value})}/></Field><Field label="Navrhovaný zástupca"><input value={editing.proposedDeputy} onChange={e=>setEditing({...editing,proposedDeputy:e.target.value})}/></Field><Field label="Potvrdený zástupca"><input value={editing.confirmedDeputy} onChange={e=>setEditing({...editing,confirmedDeputy:e.target.value})}/></Field><Field label="Rozsah zastúpenia"><textarea value={editing.scope} onChange={e=>setEditing({...editing,scope:e.target.value})}/></Field><Field label="Runbook"><textarea value={editing.runbook} onChange={e=>setEditing({...editing,runbook:e.target.value})}/></Field><Field label="Miesto dokumentácie"><input value={editing.location} onChange={e=>setEditing({...editing,location:e.target.value})}/></Field><Field label="Termín odovzdania"><input type="date" value={editing.handoverDue} onChange={e=>setEditing({...editing,handoverDue:e.target.value})}/></Field><Field label="Dátum testu"><input type="date" value={editing.testDate} onChange={e=>setEditing({...editing,testDate:e.target.value})}/></Field><Field label="Výsledok testu"><input value={editing.testResult} onChange={e=>setEditing({...editing,testResult:e.target.value})}/></Field><Field label="Poznámka"><textarea value={editing.note} onChange={e=>setEditing({...editing,note:e.target.value})}/></Field></div><div className="modal-actions"><button className="button button-ghost" onClick={()=>setEditing(null)}>Zrušiť</button><button className="button button-primary" onClick={save}><Icon name="check"/> Uložiť</button></div></Modal>}
  </>
}
